### ISSUE TITLE
Error  running script

### ISSUE THREAD

**Issue by psmedley** [fkhera/powerwallCloud#11]
Hi,

I'm getting the following error running 'python powerwallDriver.py tou'

Opening session with login
Coming to non MFA flow:
Traceback (most recent call last):
  File "/home/psmedley/authtoken.py", line 227, in authenticate
    code_url = resp.headers["location"]
  File "/home/psmedley/.local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
Traceback (most recent call last):
  File "/home/psmedley/powerwallBackup.py", line 70, in main
    tpw.productlist()
  File "/home/psmedley/powerwallBackup.py", line 134, in productlist
    result = json.loads(result.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I've created the accounts.txt per the youtube instructions, and also  put the local  IP of  my  powerwall in powerwallTimeOfUseCheck.py and powerwallBackup.py

Do  I also need to change password = 'ST17I0012345' in those scripts? Should this be the serial number of  the Gateway?

**Comment by psmedley** [comment]
Could this also be as I have two  Powerwalls  in two different sites,  so the script  doesn't know which to update?

**Comment by fkhera** [comment]
If would do both locations but recently tesla uses stricter policy to get
tokens. I don’t believe they have fixed it.

**Comment by psmedley** [comment]
So the script is broken for everyone right now?

Is  there a way to only update _one_ of my Powerwalls? they are at different sites and on different energy plans

**Comment by gdotp01** [comment]
I've been using this for a few months now and its worked really well. However a few days ago it stopped and Im not sure why. Looking at this thread Im assuming that Tesla have changed something or is that a wrong assumption?  My error is:

Processing:  grahampowell@email.com
Invoking mode:  tou
('back up attempts count: ', 0)
authenticating
('token auth attempts count: ', 0)
authenticating
Got token details
{u'expiredate': u'2022-01-17T00:31:09.702245', u'access_token': u'eu-f9c3c93ed81209f11cd4c013a1a48d5b2fe522a8eb35b3deda2d1659c8da9581', u'created_at': 1638491469, u'expires_in': 3888000, u'token_type': u'bearer', u'user': u'grahampowell@email.com', u'refresh_token': u'f32fdb2863b3521f8c7ec13a2f04f0f537ac1c2cefdbcadf494355a9af1bd8fc'}
Traceback (most recent call last):
  File "/home/pi/powerwallBackup.py", line 70, in main
    tpw.productlist()
  File "/home/pi/powerwallBackup.py", line 134, in productlist
    result = json.loads(result.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded



Any ideas ?

**Comment by fkhera** [comment]
Token expired and tesla does not allow New tokens but there is apps out
there to get a token your token expire date 1-17

**Comment by gdotp01** [comment]
Hi thanks can you explain a bit more please. How would I get a new token?

**Comment by gdotp01** [comment]
Hi again !  I think i've generated a new token but don't know what to do with it now. I can see there is a token.db file and it does contain my previous token but it also contains information that I don't have such as expiredate, createdate etc 

How do i refresh the data in this using my new token ?

**Comment by fkhera** [comment]
Change the token field that starts with like qts and change the expire date
to something in future

**Comment by fkhera** [comment]
I got some working code, (I only use Mac currently for this), I installed
selenium, chrome driver etc.
It appears if you use this combination the browser thinks you are a real
user, no captcha none of that.
This allows you to easily get the code.
THe only downside I have seen is , need to run browser mode, let it open
browser not headless.
Also if you run too many accounts too quickly the firewall seems to pick up
on that, slowly process 1 at a time.

Good luck
https://github.com/fkhera/powerwallCloud/blob/master/authtoken.py

Using this code in combination in package then you can get the auth  tokens

you can use this file to generate token.db file and replace the token.db
file and it should be okay.

**Comment by fkhera** [comment]
Here is sample data in token.db file that went bad:

{"expiredate": "2022-03-01T08:59:25.142461", "access_token":
"qts-988a973fe27a6e63abcd", "created_at": 1642262364, "expires_in":
3888000, "token_type": "bearer", "user": ***@***.***", "refresh_token":
"77d53ace39dfeb70101953ab9d8e913d533b41b626a3083d613ce3e42c31213d"}

So the expiredate may say a date in Jan, needs to change you could use data
above if you wish
access token is qts-abcd and refresh token can probably leave alone.

-Farooq

**Comment by gdotp01** [comment]
When you say the token that starts with qts do you mean the "Access Token :" 

mine does not start with qts it starts with eu-

There is one in the database that starts QTS but i think it's one of your old ones.

**Comment by fkhera** [comment]
Yes access_token field

**Comment by gdotp01** [comment]
Many thanks for your help. Thats working again with my new token

**Comment by fkhera** [comment]
Token is only good for 45 days so they say .

**Comment by gdotp01** [comment]
Yes which is a shame. However by then the weather will be better here and hopefully I won't need to manually set it over the summer.

**Comment by gdotp01** [comment]
hi.
The script has been running fine but recently stopped. I assumed it was because of the API key had expired so did my normal refresh. However this time i tried it the API key returned as a LOT longer than previously. I added it to the token.db file anyhow and it worked. However 24 hours later it stopped again. It seems now that it expires really quickly. i get the following error when running powerwallDriver.py.

Traceback (most recent call last):
  File "/home/pi/powerwallBackup.py", line 70, in main
    tpw.productlist()
  File "/home/pi/powerwallBackup.py", line 136, in productlist
    productListItems = result["response"]
KeyError: 'response'

Any ideas what has changed ?

**Comment by gdotp01** [comment]
After some research it looks like the API key expires now every 5 hours. It’s beyond me to fix this. I’ve seen that the the utility that runs ion smarthings has been updated to work around the problem

**Comment by jasonacox** [comment]
If you are looking for a way to set-reserve via cron, there is an alternative method using the [TeslaPy](https://github.com/tdorssers/TeslaPy) module that requires some user setup (pasting URL to get token) but doesn't seem to expire (at least as frequently - been using for >month). Here is the implementation I'm using: https://github.com/jasonacox/pypowerwall/tree/main/tools#set-reserve - The same approach may work here.
