### ISSUE TITLE
Error starting powellwallDriver.py (from youtube)

### ISSUE THREAD

**Issue by gdotp01** [fkhera/powerwallCloud#9]
Hi. I reported this initially via youtube and you suggested sensibility that we continue the discussion here:

I've set up a new Pi Zero (for testing). Installed all the relevant packages (as far as I can't tell) and set up a recaptcha account from your link. I've added the API key from my recaptcha into recaptchasolver.py as below: (I've anatomised Key) 

"API_KEY = 'b349e080ca4e1ea3e447724bfa5aaXXX'  # Your 2captcha API KEY
CAPTCHA_ENABLE = True"

When I try and run "powerwallDriver.py backup" I get the following errors (Keys analonomised again) which seems to fail with an "list index out of range" error.  Any help would be greatly appreciated as my lack of control of the Powerwall at the moment is very frustrating as it gets its APOI guess wrong almost every day at the moment on how to charge from off-peak (UK user) 

Processing:  grahampowell@email.com
Invoking mode:  backup
('back up attempts count: ', 0)
authenticating
('token auth attempts count: ', 0)
authenticating
authenticate method
getting url
https://auth.tesla.com/oauth2/v3/authorize?code_challenge=hFuP9jZsXqWNeUIooUjcSV6NLuCXD8XXXX-QKOfcBY&client_id=ownerapi&state=tesla_exporter&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&response_type=code&code_challenge_method=S256&scope=openid+email+offline_access
captcha sitekey: 6LdUQhgUAAAAAEe8NWX3Rur9bQRqq-2RUPhthXXX
auth url: https://auth.tesla.com/oauth2/v3/authorize?code_challenge=hFuP9jZsXqWNeUIooUjcSV6NLuCXD8X6XXX-QKOfcBY&client_id=ownerapi&state=tesla_exporter&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&response_type=code&code_challenge_method=S256&scope=openid+email+offline_access
Getting captcha
Traceback (most recent call last):
  File "/home/pi/authtoken.py", line 207, in authenticate
    captchacode = recaptchasolver.main(recaptcha_site_key, auth_url)
  File "/home/pi/recaptchasolver.py", line 37, in main
    captcha_id = resp.text.split('|')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/powerwallBackup.py", line 70, in main
    tpw.productlist()
  File "/home/pi/powerwallBackup.py", line 137, in productlist
    count = int(result["count"])
KeyError: 'count'

**Comment by gdotp01** [comment]
Yes but that's not the error Im getting. The2capture  API returns error codes and I'm not getting one  in the above. 

"File "/home/pi/authtoken.py", line 207, in authenticate" is a call to 2capture but their documentation says that it will return a code of "No Credit" if that's the case

**Comment by gdotp01** [comment]
No. If I use the Auth link I get "Page not Found" assuming that the auth link is the one following 'auth url :"

**Comment by gdotp01** [comment]
Sorry being a bit dense. What do you mean? I don't see anything that looks like "waiting, waiting, solving" it errors immediately after the line that says "Getting captcha"

**Comment by fkhera** [comment]
So was main problem no credits in 2capture?
